### ISSUE TITLE
1.4.0-beta: inconsistency of file name

### ISSUE THREAD

**Issue by microdou** [kevinkovalchik/RawTools#13]
**Describe the bug**
Introduced in 1.4.0-beta, parsed file name is now `*.raw._parse.txt` instead of `*.raw_Matrix.txt`.
To be consistent with the names of the other exported files, you may want to remove the `.` in front of `_parse.txt`. Other parsed files all have names in the form of `*.raw_**.txt`

**Comment by kevinkovalchik** [comment]
Sorry, yes I know about this one. I've fixed it and will put up a new file
later today. I'm not at work today, but will hopefully have time this
evening to get to it.

Kevin

**Comment by kevinkovalchik** [comment]
1.4.0-beta.2 is now released and the output filenames have been corrected.

Kevin
