### ISSUE TITLE
_matrix file not generated when using -q argument (1.4.0-beta)

### ISSUE THREAD

**Issue by ncarrut** [kevinkovalchik/RawTools#16]
**Describe the bug**
rawTools-1.4.0 fails to generate _Matrix file.  _log file is created and seems ok.  _parse and _Metrics files are also created when using the appropriate command.  It just seems to be quantification.  
**Edit** 
I also tried 1.3.3 and that works to make the _Matrix file.

**Description of raw file**
DDA TMT MS2 Fusion mass spec.  

**Command line arguments**
C:\Users\Proteomics\Documents\Analysis\Panc_ARP_N>RawTools parse -f C:\Users\Pro
teomics\Documents\Analysis\Panc_ARP_N\Panc_TMT-N_ARP_07.raw -q -r TMT10

**Command line output**
```

Determing MS analysis order... Done!
Extracting scan indices: 100%
Checking for orphaned scans: 100%

================ Scan indexing report ================
Total scans in file: 28045
Scans linked: 28045

Orphan scans:
None!

All scans accounted for!
======================================================

Extracting scan data: 100%
Extracting trailer extras: 100%
Extracting precursor masses: 100%
Extracting retention times: 100%
Quantifying reporter ions: 100%

Elapsed time: 15.05 s

Time to process all 1 files: 00:00:15.0540778

```

**Screenshots**

**Desktop & RawTools information:**
rawTools 1.4.0 beta
Windows 7 on a dell XPS 8500 
[rawtools_log.txt](https://github.com/kevinkovalchik/RawTools/files/2696418/rawtools_log.txt)

Intel i7-3770

**Additional context**

**Comment by kevinkovalchik** [comment]
Yes, I was missing a check for the -q flag in part of the workflow! This should be fixed now.
Try using `RawTools-1.4.0-beta.4.zip` and let me know if that fixes the issue for you.

Kevin
