### ISSUE TITLE
mono RawTools.exe returns System.IO.FileNotFoundException

### ISSUE THREAD

**Issue by soerendip** [kevinkovalchik/RawTools#23]
I am trying to setup RawTools with mono on a Ubuntu 16.04 system. I just installed mono and copied the RawTools files from my notebook to the new system. So, things should be identical now, but I get the following error. Any idea what is going on? Am I missing something?

> Unhandled Exception:
> System.IO.FileNotFoundException: Could not load file or assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
> File name: 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
>   at Serilog.Parsing.MessageTemplateParser.Parse (System.String messageTemplate) <0x41af0fb0 + 0x0004f> in <filename unknown>:0
>   at Serilog.Formatting.Display.MessageTemplateTextFormatter..ctor (System.String outputTemplate, IFormatProvider formatProvider) <0x41af0ea0 + 0x00047> in <filename unknown>:0
>   at Serilog.FileLoggerConfigurationExtensions.File (Serilog.Configuration.LoggerSinkConfiguration sinkConfiguration, System.String path, LogEventLevel restrictedToMinimumLevel, System.String outputTemplate, IFormatProvider formatProvider, Nullable`1 fileSizeLimitBytes, Serilog.Core.LoggingLevelSwitch levelSwitch, Boolean buffered, Boolean shared, Nullable`1 flushToDiskInterval, RollingInterval rollingInterval, Boolean rollOnFileSizeLimit, Nullable`1 retainedFileCountLimit, System.Text.Encoding encoding) <0x41af0d10 + 0x00073> in <filename unknown>:0
>   at RawTools.Program.Main (System.String[] args) <0x41aecf70 + 0x00203> in <filename unknown>:0
> [ERROR] FATAL UNHANDLED EXCEPTION: System.IO.FileNotFoundException: Could not load file or assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
> File name: 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
>   at Serilog.Parsing.MessageTemplateParser.Parse (System.String messageTemplate) <0x41af0fb0 + 0x0004f> in <filename unknown>:0
>   at Serilog.Formatting.Display.MessageTemplateTextFormatter..ctor (System.String outputTemplate, IFormatProvider formatProvider) <0x41af0ea0 + 0x00047> in <filename unknown>:0
>   at Serilog.FileLoggerConfigurationExtensions.File (Serilog.Configuration.LoggerSinkConfiguration sinkConfiguration, System.String path, LogEventLevel restrictedToMinimumLevel, System.String outputTemplate, IFormatProvider formatProvider, Nullable`1 fileSizeLimitBytes, Serilog.Core.LoggingLevelSwitch levelSwitch, Boolean buffered, Boolean shared, Nullable`1 flushToDiskInterval, RollingInterval rollingInterval, Boolean rollOnFileSizeLimit, Nullable`1 retainedFileCountLimit, System.Text.Encoding encoding) <0x41af0d10 + 0x00073> in <filename unknown>:0
>   at RawTools.Program.Main (System.String[] args) <0x41aecf70 + 0x00203> in <filename unknown>:0

**Comment by soerendip** [comment]
This is a mono issue. Installing mono-complete solved it.

`apt install mono-complete`

**Comment by kevinkovalchik** [comment]
Oh, good. Thanks for letting me know.

Kevin
