### ISSUE TITLE
System.MissingMethodException: Method 'Array.Empty' not found.

### ISSUE THREAD

**Issue by soerendip** [kevinkovalchik/RawTools#26]
**Describe the bug**
I have MS2 data from a bacterial sample. I wanted to generate peaklists from it for further analysis. I can create the raw_Matrix.txt files. Though no mgf files are generated. 

I tried a minimal command an ran `RawTools parse -f 1_A.raw -m` and got the following output:

> Processing: 1_A.raw
> 
> Indexing linked scan events: 100%                                                                                    
>                                                                                                                      
> 
> Unhandled Exception:
> System.MissingMethodException: Method 'Array.Empty' not found.
>   at RawTools.Program.DoStuff (RawTools.ArgumentParser.ParseOptions opts) <0x41315410 + 0x00f7f> in <filename unknown>:0 
>   at RawTools.Program+<>c.<Main>b__0_0 (RawTools.ArgumentParser.ParseOptions opts) <0x413153e0 + 0x00013> in <filename unknown>:0 
>   at CommandLine.ParserResultExtensions.WithParsed[T] (CommandLine.ParserResult`1 result, System.Action`1 action) <0x413152c0 + 0x000d2> in <filename unknown>:0 
>   at RawTools.Program.Main (System.String[] args) <0x412a1f70 + 0x00337> in <filename unknown>:0 
> [ERROR] FATAL UNHANDLED EXCEPTION: System.MissingMethodException: Method 'Array.Empty' not found.
>   at RawTools.Program.DoStuff (RawTools.ArgumentParser.ParseOptions opts) <0x41315410 + 0x00f7f> in <filename unknown>:0 
>   at RawTools.Program+<>c.<Main>b__0_0 (RawTools.ArgumentParser.ParseOptions opts) <0x413153e0 + 0x00013> in <filename unknown>:0 
>   at CommandLine.ParserResultExtensions.WithParsed[T] (CommandLine.ParserResult`1 result, System.Action`1 action) <0x413152c0 + 0x000d2> in <filename unknown>:0 
>   at RawTools.Program.Main (System.String[] args) <0x412a1f70 + 0x00337> in <filename unknown>:0 
> 

**Description of raw file**
It is MS2 data from an Orbitrap. The file is ~2GB in size.

**Comment by kevinkovalchik** [comment]
So this happens when you use `RawTools parse -f 1_A.raw -m` but not when you use `RawTools parse -f 1_A.raw -p`? Which version of RawTools are you using?

**Comment by kevinkovalchik** [comment]
Also, does this happen for all your raw files or just this one?

**Comment by soerendip** [comment]
Apparently, this was an error related to `mono`. I installed version `5.14.0.177`. Now, the mgf files are generated. With `RawTools parse -f file.raw -m`.

**Comment by kevinkovalchik** [comment]
Okay. Thanks for letting us know!
