### ISSUE TITLE
未经处理的异常:  System.ComponentModel.Win32Exception: 拒绝访问

### ISSUE THREAD

**Issue by marcos914** [kevinkovalchik/RawTools#27]
**Describe the bug**
When I run the last command with identipy，
RawTools qc -d G:\RENZHE\rawtools -q G:\RENZHE\rawtools\qc_output_wSearch\ -i --db G:\RENZHE\rawtools\uniprot_human.fasta --fmods 57.0214@C --xmod 15.9949@M -N 1000
Checking Identipy dependencies
The following error occurred：System.ComponentModel.Win32Exception: 拒绝访问，
Although I can use xtandem for quality control

**Comment by kevinkovalchik** [comment]
Hello,

Have you tried using `-P` and `-I` to specify the locations of the Python executable and the IdentiPy script? For example:
```
RawTools -qc -d C:\MyRawFiles -q C:\MyRawFiles\QcOutput
-s identipy -P C:\Python27\python.exe -I C:\Python27\Scripts\identipy-script.py --db C:\MyRawFiles\uniprot_human.fasta
```

Kevin
