### ISSUE TITLE
More consistent column/row names

### ISSUE THREAD

**Issue by soerendip** [kevinkovalchik/RawTools#35]
Hi, 

I noticed that the column/row names have different formats and even different names for the same content in the files generated by RawTools. For example, the metrics file contains the field RawFile that contains the path of the raw file, while in the QcDataTable the column name is called FileName. Some other examples:

The QcDataTable:
Ms1ScanRate(/s)	
MedianMs3FillTime(ms)

The Metrics file:
TotalAnalysisTime(min):	
MS1ScanRate(/sec):	
MedianPeakWidthAt10Percent(s):	

My suggestion is to use the same format for the units, preferably something like [1/s] with square brackets and SI-units, in all files and use the same identifier for the same contents.

**Comment by kevinkovalchik** [comment]
Hi Soren,

Thanks for bringing this up. I'm working on some other updates that I plan to release in the the next month or two. I'll be sure to address this as well, unless it would help you to have it done sooner. Is this something that is impeding your workflows right now, or does it just bother your good sense? :)

Kevin

**Comment by soerendip** [comment]
Just a sense of consistency. I can rename the fields.

**Comment by kevinkovalchik** [comment]
Hi @soerendip,

v2.0.0 just got released. I made an effort to align all the metric names between the different data files. Let me know if you see anything else to fix.

Also, as we talked about quite a while ago, the "parse" and "qc" functions are no longer separate. You can mix whatever parts of the parse functionality you want in with qc.
