### ISSUE TITLE
Extracting & plotting peptide/protein results from X!tandem search

### ISSUE THREAD

**Issue by roberthardt** [kevinkovalchik/RawTools#37]
**Is your feature request related to a problem? Please describe.**
Currently just a few metrics are taken from the X!tandem search and plottet by the Shiny app. 

**Describe the solution you'd like**
It would be fantastic to plot also things like the peptide scores, average peptide scores, proteins cores, protein sequence coverage. Since we always run the same sample (BSA digest) for our QC, we are interested how good the identification was in each run.

**Describe alternatives you've considered**

**Additional context**

**Comment by kevinkovalchik** [comment]
Thanks for the suggestion. I don't think the "preview" search we do would
be adequate for things like protein coverage, so those metrics would
probably need to trigger a full search, which is not a problem. It'll just
take longer. I'll talk with Chris about it and get back to you to
discuss further.

Kevin

**Comment by kevinkovalchik** [comment]
@roberthardt We don't want to get too specific with the QC metrics, as we are more interested in observing consistency rather than monitoring a specific QC cutoff. However, you are right that there is some room for additional features here. I am going to look into adding these metrics to the QC data:

- Median peptide score
- Decoy score cutoff value
- Number of PSMs
- Number of unique peptides

**Comment by roberthardt** [comment]
Hi Kevin,

Thanks for your quick reply and the future implementation of the additional database search derived metrics. Having those additional informations in the QC table would allow us assessing our LC-MS systems in a fast and convenient way. Currently we do those things manually, which is very time consuming and tedious. 

Best regards

Robert 

--------------------------
Dr. Robert Hardt
Emser Str. 32
65195 Wiesbaden 
Tel.: +49-176-61573795

**Comment by kevinkovalchik** [comment]
Hi @roberthardt,

v2.0.0 was just released today and includes the metrics mentioned above.

Let us know if there are other improvements you'd like to see!

Kevin
