### ISSUE TITLE
Additional useful metric/setting suggestions

### ISSUE THREAD

**Issue by roberthardt** [kevinkovalchik/RawTools#38]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
1. Would it possible to also state the average number of datapoints over the MS1-peaks? This is usually quite helpful to assess how good your quantification could be.
2. I browsed through some of my data using the Shiny-app. Would it be possible to add a file/lc-ms run filter function in this, which directly affects the plots? With this one could then simply get plots for a subgroup of raw files.

**Describe alternatives you've considered**
---

**Additional context**
---

Thanks again for the great tool you provided for the community.

Best

Robert

**Comment by roberthardt** [comment]
Hi Kevin,

Thanks again for the immediate reply. 

Regarding point 1:
I’m interested in first, the number of dda cycles. I know there is the cycle time and I could easily calculate that by taking the peak width and dividing it by the cycle time, but I rather have a separate metric. 

2. Here I’m interested in being able to do the later i.e. more advanced filtering. I for example usually run low complex (BSA) as well as high complex (HeLa) samples on our mass specs. Filtering the results for either one of those would be great. Here I could work with different QC csv files for each sample type, but a filtering option would be the more elegant solution. 

I am also excited about the future new visualization tool. Trying to finish it until ASMS?😉

Keep up the good work

Best Robert 

--------------------------
Dr. Robert Hardt
Emser Str. 32
65195 Wiesbaden 
Tel.: +49-176-61573795

**Comment by kevinkovalchik** [comment]
Haha, no unfortunately and oddly the CSC conference and ASMS are concurrent this year and I'm presenting at CSC.

Okay, those should be easy to incorporate. For 2, a simple text search will definitely work (e.g. filter for "bsa" in the filename). I can enable regular expressions if something fancier is desired, but I imagine that would be overkill.

**Comment by kevinkovalchik** [comment]
Hi @roberthardt,

These changes have been made in v2.0.0. For the filtering, we didn't go as far as allowing for regex expressions, but there is a simple text filter for raw file names. For example, if you filter for "HeLa", it will display data only for raw files with "HeLa" as part of the filename. Let me know more flexible filtering would be helpful.

Kevin

**Comment by roberthardt** [comment]
Hi Kevin,

thanks for the new version of RawTools and implementing my suggestions. I
will check it out right now. :-)

Best

Robert

Am Mi., 3. Juli 2019 um 23:17 Uhr schrieb Kevin Kovalchik <
notifications@github.com>:

**Comment by roberthardt** [comment]
Hi Kevin,

The visualization tool always crashes when I'm trying to load in any result
created by RawTools. Did I necessarily have to install Thermo's
new RawFileReader first?

best

Robert

Am Do., 4. Juli 2019 um 11:17 Uhr schrieb Robert Hardt <
roberthardt@gmail.com>:

**Comment by kevinkovalchik** [comment]
Hi Robert,

Sorry about that. Can you tell me what operating system you are using? And
is an error message popping up or is the tool just closing when you try to
open something?

Kevin

**Comment by kevinkovalchik** [comment]
Oh, I see. I can't even run it myself... well that's embarrassing. I must
have forgotten to copy some settings in the release build. I tested it, but
it must have still been running the debug version. I'll see if I can get
this fixed ASAP!

**Comment by kevinkovalchik** [comment]
Okay, I fixed it! Please try v2.0.1.

Sorry again, I should have caught that before the release.

Kevin
