### ISSUE TITLE
Not able to install rawtools with pip anymore.

### ISSUE THREAD

**Issue by soerendip** [kevinkovalchik/RawTools#52]
I used to install rawtools with `conda create -n env -c conda-forge rawtools`. That does not seem to work anymore. Is it due to my python version 3.8.3 or was the package remove from the python index? I cannot find information about installing rawtools other than from source. Is that the recommended way of installing rawtools?

**Comment by soerendip** [comment]
`conda install -c bioconda rawtools` works

**Comment by kevinkovalchik** [comment]
Okay, glad it is working through bioconda! RawQuant was a python package
and should install through pip (though I don't know about 3.8+), but
RawTools is a .NET program. Nice to know it is on Bioconda, though. I
didn't know it got put up there.
