### ISSUE TITLE
Using Matrix data with quant to assign spectra to TMT-10 plex samples

### ISSUE THREAD

**Issue by andreabc** [kevinkovalchik/RawTools#60]
Hello,

Thanks for creating an awesome tool and wiki! I'm new to mass spec analysis and was wondering if it is possible to use the reporter ion information (e.g. intensity/resolution) in the Matrix quant data to assign a spectrum to one or more of the TMT labels? Would it make sense to take the maximum intensity of all the reporter ions?  

Thanks a bunch,
Andrea

**Comment by chrishuges** [comment]
Hi Andrea,

I am not sure exactly what you mean here. Can you provide an example of what result you were hoping to get so I can better judge if RawTools can help you?

Thanks,
Chris

**Comment by chrishuges** [comment]
Closed due to lack of response. Will re-open if desired.
