### ISSUE TITLE
How to run label-free quant? I guess its -u the parameter, but the results are not including right ions

### ISSUE THREAD

**Issue by CandyClass** [kevinkovalchik/RawTools#67]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by chrishuges** [comment]
Can you please provide some more details? It is indeed the -u flag, but what do you mean it is not including the right ions? Can you provide an example?

**Comment by chrishuges** [comment]
Closed due to lack of response. Will re-open if desired.
