### ISSUE TITLE
Does RawTool support Iodo-TMT ?

### ISSUE THREAD

**Issue by sorenwacker** [kevinkovalchik/RawTools#68]
I wonder whether RawTools does support Iodo-TMT ?

**Comment by chrishuges** [comment]
Correct me if I am wrong, but aren’t the reporter ions for iodo-TMT the
same as for normal TMT? I think it should work without issue in that case.

Chris

**Comment by sorenwacker** [comment]
Good question. I saw that MaxQuant makes a difference between TMT-6 and Iodo-TMT6. Just want to make sure that if I get results they are correct.

**Comment by kevinkovalchik** [comment]
MaxQuant would have the two options because the modification masses are
different and they label different residues. If I recall correctly,
RawTools only deals with the reporter masses, so it shouldn't matter.

Kevin

**Comment by sorenwacker** [comment]
Thank you!
