### ISSUE TITLE
Typo in QC csv columns?

### ISSUE THREAD

**Issue by kesinger** [kevinkovalchik/RawTools#70]
**Describe the bug**

Line 540 in RawTools/Write/DataWrite.cs has "MedianMs1IsolationInterence" instead of (presumably) "MedianMs1IsolationInterference".

**Comment by chrishuges** [comment]
Thank you for bringing this to our attention. We will fix this in an upcoming release.

**Comment by chrishuges** [comment]
Fixed in [2.0.4](https://github.com/kevinkovalchik/RawTools/releases).
