### ISSUE TITLE
Missing zip file for the most recent release.

### ISSUE THREAD

**Issue by dpryan79** [kevinkovalchik/RawTools#72]
It looks like the zip file for version 2.0.4 ( https://github.com/kevinkovalchik/RawTools/releases/download/2.0.4/RawTools-2.0.4.zip) got removed at some point. Over at bioconda I'm seeing an error when trying to download it and I also don't see it here on github.

**Comment by chrishuges** [comment]
2.0.4 is posted again. Sorry for the delay.

**Comment by dpryan79** [comment]
Awesome, thanks!
