### ISSUE TITLE
Installation fails: Error in htmlDependency("font-awesome", "5.3.1", "www/shared/fontawesome",  : 

### ISSUE THREAD

**Issue by SamGG** [kevinkovalchik/RawTools#9]
Starting from a fresh R 3.5.1 on Windows 7 x64 with Rtools35, we installed the various packages needed by RawTools
```
install.packages(c("shiny", "ggplot2", "reshape2", "RColorBrewer", "data.table", "shinydashboard"))
```
When running the shiny app, an error appears:
```
Error in htmlDependency("font-awesome", "5.3.1", "www/shared/fontawesome",  : 
unused argument (package = "shiny")
```
![2018-11-28_181057](https://user-images.githubusercontent.com/3333348/49169613-6ac8d700-f33a-11e8-8a70-f212383f23eb.png)

This error has been referenced at https://community.rstudio.com/t/r-shinydashboard-instructions-doesnt-work/18000/3. Installing the latest htmltools v 0.3.6 from source solves the error.
```
install.packages("htmltools")
```
For installation from source, you must install Rtools with administrative permissions and add R tools to the PATH.
HTH

**Comment by chrishuges** [comment]
Thanks for the heads up. I just added some code to the Shiny app to check whether all required libraries are present, and if not, to install them (including htmltools). Will post the updated version here in the next day or so.

Note for RStudio users - admin is not required to run this package through RStudio. 

Cheers,
Chris

**Comment by SamGG** [comment]
Thanks. I think you should let the issue open until your really updated the repo in order to allow users to catch the solution here.
Best.

**Comment by chrishuges** [comment]
Sorry, when I saw the updated version will be posted in the next day or so, I meant in the online web interface. The source code version is posted. I should have been more specific.

**Comment by chrishuges** [comment]
True, good catch! I will fix this and update the source file. It should always install the latest htmltools, so I will skip the versioning for now unless it becomes an issue for someone in the future.
